services:
  fcms-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - fcms_data:/var/lib/mysql
    networks:
      - fcms

  fcms-backend:
    build: ./api
    ports:
      - 5000:5000
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DIALECT: ${DB_DIALECT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - fcms-db
    restart: always
    networks:
      - fcms

  fcms-frontend:
    build: ./client
    ports:
      - 3000:80
    depends_on:
      - fcms-backend
    networks:
      - fcms

networks:
  fcms:
    name: fcms

volumes:
  fcms_data:
    name: fcms_data