services:
  fcms-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: faculty_db
      MYSQL_ROOT_PASSWORD: abhi1502
    volumes:
      - fcms_data:/var/lib/mysql
      # - /home/abhinav-bagalkot/data:/var/lib/mysql
    networks:
    - fcms
  fcms-backend:
    # image: fcms-backend:1.2
    build: ./api
    ports:
    - 5000:5000
    environment:
     DB_USER: root
     DB_PASS: abhi1502
     DB_NAME: faculty_db
     DB_HOST: fcms-db
     DB_PORT: 3306
     DB_DIALECT: mysql
     JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - fcms-db
    restart: always
    networks:
    - fcms
  fcms-frontend:
    # image: fcms-frontend:1.1
    build: ./client
    ports:
    - 3000:3000
    networks:
    - fcms
networks:
  fcms:
    name: fcms
volumes:
  fcms_data:
    name: fcms_data